### ISSUE TITLE
Doesn't work on Github Actions running JDK 18

### ISSUE THREAD

**Issue by mineblock11** [PacifistMC/Forgix#15]
```
 > Task :mergeJars FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mergeJars'.
> Cannot read the array length because "<local17>" is null
```

https://github.com/KyaniteMods/DeeperAndDarker/actions/runs/3073505090/jobs/4965680591

**Comment by Ran-Mewo** [comment]
Weird
have to look into what's `<local17>`

Also GitHub actions _(at least on my repo)_ works so it shouldn't be specifically coming from that
might be something with the adopt distribution of Java
