### ISSUE TITLE
':mergeJars' NoSuchFileException: .gradle\forgix\duplicate-temps

### ISSUE THREAD

**Issue by DanHCraft** [PacifistMC/Forgix#16]
I want to build a foreign project ([Distant Horizons](https://gitlab.com/jeseibel/minecraft-lod-mod)) and the following error occured:
```
Execution failed for task ':mergeJars'.
> java.nio.file.NoSuchFileException: F:\Programming\Java\Minecraft\Mods\minecraft-lod-mod\.gradle\forgix\duplicate-temps
```
I tried to create a directory named `duplicate-temps` but this also fails.
Command Output: https://gist.github.com/DanHCraft/356ba95379c34081ffe391c6ba7a5d00

**Comment by Ran-Mewo** [comment]
I am actually one of the developers of Distant Horizons
The current build system of Distant Horizons is actually really off
I am supposed to be the one fixing it but I can't really work on the mod at the moment because of my health issues

I'll look more into the issue after I get well

**Comment by Ran-Mewo** [comment]
Oh yeah I don't this is an issue any longer
so I'll be closing this

**Comment by Faboslav** [comment]
So, what was the solution for this? I am currently in the process of adapting my architectury setup for forgix, but i am having this issue and i am not sure what to do about it
