### ISSUE TITLE
Build failing due to NPE in FileUtils

### ISSUE THREAD

**Issue by zbx1425** [PacifistMC/Forgix#25]
```
Caused by: java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "type" is null
	at io.github.pacifistmc.forgix.utils.FileUtils.isMagicCharacter(FileUtils.java:311)
```

https://github.com/PacifistMC/Forgix/blame/7393708293d724613ab141aa2e5b69ffe6c4f646/src/main/java/io/github/pacifistmc/forgix/utils/FileUtils.java#L311

Turns out somehow `Files.probeContentType` can return `null`...

**Comment by hypherionmc** [comment]
Have to say, I can confirm that behavior. I ran across it in a discord bot of mine.

@Ran-Mewo I'll submit the fix I did in modpublisher (which seems to work well) tonight :)

**Comment by Ran-Mewo** [comment]
@hypherionmc did you submit it yet?

**Comment by hypherionmc** [comment]
Ah shoot no. Sorry, will do it first thing after work
