### ISSUE TITLE
Unable to update to 1.2.8 from 1.2.6/1.2.7

### ISSUE THREAD

**Issue by LoxiGoose** [PacifistMC/Forgix#27]
Hiya! Not sure if I am doing anything wrong but I am noticing that the new update is erroring my gradle on reload because of its inability to find something called "JarManager".

Error:
`Could not find fr.stevecohen.jarmanager:JarManager:0.5.0`

Because of the above error, I tried adding the repository that provides JarManager but I just keep getting "Already seen doctype" errors + it is unable to parse the POM anyways.

Looking further into the issue, I did notice that a line in build.gradle was changed in the new 1.2.8 update to directly reference JarManager. Perhaps that may be the problem?
`shadowMe fileTree(dir: 'libs', include: ['*.jar'])` (1.2.7)
`shadowMe 'fr.stevecohen.jarmanager:JarManager:0.5.0'` (1.2.8)

https://github.com/PacifistMC/Forgix/blob/ab3351a5d68bc5cf5e0aed3e221b014dad142289/build.gradle#L34 (1.2.7)
https://github.com/PacifistMC/Forgix/blob/e1635e979d4831cd662a812cf4aeb7762d0fbc0b/build.gradle#L41 (1.2.8)

Is this an issue on my end or is it something you have to fix? Sorry if there is an obvious fix that can be done on my end, I am not the best at gradle and I am not sure how I would bypass this problem.

**Comment by hypherionmc** [comment]
I submitted a fix for this. Ran just has to publish it :)

For a now, work around is to do the following:

In your `settings.gradle` file, add this to the top:

```groovy
pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            url "https://maven.firstdark.dev/releases"
        }
    }
}
```

If you already have a `pluginManagement` block in there, just add the following under `gradlePluginPortal()`

```groovy
 maven {
    url "https://maven.firstdark.dev/releases"
}
```

**Comment by Ran-Mewo** [comment]
I literally made sure this didn't happen before publishing the new update
and it's exactly what happened
![](https://media.discordapp.net/stickers/953002645646348288.webp?size=160)

**Comment by Ran-Mewo** [comment]
Sorry for all the inconvenience but everything should **hopefully** work with version 1.2.9!

**Comment by hypherionmc** [comment]
🥳 Also, hey Loxi. I just recognized your 🤦‍♂️
