### ISSUE TITLE
Forgix changing JSON files inside data directory?

### ISSUE THREAD

**Issue by Kitteh6660** [PacifistMC/Forgix#30]
I have an issue with Forgix and for some reason, it decided to rename those JSON files and thus break the mod's datapack and crashing the world creation screen.

Is there a way to stop Forgix from doing that?

![image](https://github.com/PacifistMC/Forgix/assets/5838739/85ce93fc-0bf8-4dc4-9195-5f00e5d378d4)

I'm using Forgix 1.2.9 if that helps.

**Comment by Ran-Mewo** [comment]
Could I see those files? I have a feeling it's accidentally detecting those files as mixins

**Comment by Kitteh6660** [comment]
I can do that. Those are the affected JSON files.

[fabric-patch_froglight.json](https://github.com/PacifistMC/Forgix/files/15335193/fabric-patch_froglight.json)
[forge-flower_luzawood.json](https://github.com/PacifistMC/Forgix/files/15335194/forge-flower_luzawood.json)
[forge-patch_froglight.json](https://github.com/PacifistMC/Forgix/files/15335195/forge-patch_froglight.json)
[fabric-flower_luzawood.json](https://github.com/PacifistMC/Forgix/files/15335192/fabric-flower_luzawood.json)

I will be updating my code repository so you can see what's wrong.

**Comment by Kitteh6660** [comment]
I've updated the source code: https://github.com/Kitteh6660/Ceilands

The original JSON files are stored in common.

**Comment by hypherionmc** [comment]
I think as a safety thing, we shouldn't ever touch files inside `assets` and `data`. There shouldn't ever be a case where we need to modify something there
